# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock --immediate --immediate-render
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}
