#!/usr/bin/env bash

alias p='podman'
alias k='kubectl'
alias t='terraform'
alias v='nvim .'
alias ls='ls --almost-all --color --classify --group-directories-first --human-readable -1 --time-style=long-iso'

# git

alias g='git'
alias ga='git add'
alias gb='git branch -vv'
alias gbg='LANG=C git branch -vv | grep ": gone\]"'
alias gbgD='LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '\''{print $1}'\'' | xargs git branch -D'
alias gbgd='LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '\''{print $1}'\'' | xargs git branch -d'
alias gbi='git bisect'
alias gbib='git bisect bad'
alias gbig='git bisect good'
alias gbir='git bisect reset'
alias gbis='git bisect start'
alias gbl='git blame -wCCC'
alias gc='git commit --verbose --signoff'
alias gcl='git clone --recurse-submodules'
alias gclean='git clean --interactive -d'
alias gco='git checkout'
alias gcom='git checkout $(git_main_branch)'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gf='git fetch'
alias gfa='git fetch --all --prune --jobs=10'
alias gl='git log --stat'
alias glg='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
alias glga='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
alias glp='git log --stat --patch'
alias gm='git merge'
alias gmm='git merge $(git_main_branch)'
alias gmom='git merge origin/$(git_main_branch)'
alias gmum='git merge upstream/$(git_main_branch)'
alias gp='git push -v'
alias gpF='git push -v --force-with-lease --force-if-includes'
alias gpl='git pull'
alias grb='git rebase'
alias grbm='git rebase $(git_main_branch)'
alias grbom='git rebase origin/$(git_main_branch)'
alias grbum='git rebase upstream/$(git_main_branch)'
alias gre='git reset'
alias grf='git reflog'
alias grm='git rm'
alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
alias grv='git revert'
alias gs='git status --short --branch'
alias gst='git stash'
alias gt='git tag'
alias gwipe='git reset --hard && git clean --force -df'
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtls='git worktree list'
alias gwtmv='git worktree move'
alias gwtrm='git worktree remove'

